### ISSUE TITLE
We're currently attempting to migrate this over to magento 2.1.x. Any caveats?

### ISSUE THREAD

**Issue by sprayground** [Knectar/Magento-Store-Codes#11]
Is this still the only or best way to accomplish this task on Magento 2? We have been surprised not to find much information on this and so I am porting this over to magento 2.. any caveats would be appreciated. thanks

**Comment by clockworkgeek** [comment]
I haven't had a reason to look at the store codes in Mage2 but so much else is the same as Mage1 that I almost expect this will too.  On the plus side that probably means the strategy used in this extension will likely work the same as well. The essential part is in [Router.php](app/code/community/Knectar/Storecodes/Controller/Router.php).

Good luck with your project.
