### ISSUE TITLE
Store code to website

### ISSUE THREAD

**Issue by jari646** [Knectar/Magento-Store-Codes#3]
Hello,
Is there possibility to get this to work with many websites (in one Magento installation)

I have 4 websites in my magento and all of those, I need to add new store views. All those websites have urls that are well indexed. When I test your module, it work good in my default website, but not others.

example:
www.mydomain.com (this is main website/default - work good)
www.mydomain.com/storeview1-code (work good)
-
In my second domain www.seconddomain.com I would like same result, but I get this 
www.seconddomain.com/stroview2-code
www.seconddomain.com/second-stroview2-code

Thanks
Best regards,
Jari

**Comment by clockworkgeek** [comment]
I'm certain it is possible.  And a good suggestion to, thank you.

**Comment by jari646** [comment]
Hi,
Is this something you could do to us with some time table? I could buy service from you.

**Comment by clockworkgeek** [comment]
I will now try quickly and see how complex it might be.

**Comment by clockworkgeek** [comment]
Jari,

This works in my test environment but I'd love to know it works on your real site too.

**Comment by jari646** [comment]
Thanks for this. It seams that all urls are now with out store code :(

**Comment by clockworkgeek** [comment]
Currently I don't know why.  I shall think about it for a while.

**Comment by jari646** [comment]
Have you think how we can choose main store view to every websites? One idea is to use 
- Store View Information ---- Sort Order, like 0 would be main, and other not.

**Comment by clockworkgeek** [comment]
Each store has a 'Default store view' field on the 'Manage Stores' page.  I used this to tell which store view should be excluded.  I just realised if you have many stores per website and one view per store then it will have the problem you describe.  I need to either limit it to one view per website or provide better control.

**Comment by jari646** [comment]
Yes, I have many stores in one website and those store can have 1-3 store views

This is solution, so I get new root category for all stores, and after that I can use different languages in store views.

And not to but it too easy, there is that many websites also.

**Comment by jari646** [comment]
I notice that there is same setting in Website Information "Default Store", so with this and this 
'Default store view' field on the 'Manage Stores' page.

**Comment by jari646** [comment]
Sorry to hurry you, but did you have time to check this possibility?
If we check under website what is default store and if we check from store what is default store view. We can leave all default values away from url, then this should work 100% good in any case.

I am also very glad to contribute you for this development, because I am little hurry.

Thanks

**Comment by clockworkgeek** [comment]
Limiting to one per website is closer to what I originally intended so this should be better for everyone.  I think it could be more intelligent, perhaps only allowing one code-less store per base URL.  There are several ways this could be improved...

**Comment by jari646** [comment]
This work 100% good now with all my stores and store views :)
Thanks!!!
