### ISSUE TITLE
FPC bug when using in Magento EE

### ISSUE THREAD

**Issue by mbijnsdorp** [Knectar/Magento-Store-Codes#5]
When using this module in Magento Enterprise, you get 404 pages which cannot be redirected to the correct page by the same logic you do it normally.
The targetPath becomes "pagecache/request/noRoute", and thus far I have not found a way to redirect it to the correct page.

I'm working on trying to get this fixed, will let you know if I find anything.

**Comment by clockworkgeek** [comment]
This is good to know but I wasn't able to recreate it on a fresh install of EE 1.14.2.  Which branch did you try?  The [newer one](https://github.com/Knectar/Magento-Store-Codes/tree/unique-domain) works in a different (better) way but it hasn't been used on a real site yet.

**Comment by mbijnsdorp** [comment]
I used the dev-master version and now also tried the new branch, but both result in the same issue. Also using Magento 1.14.2

**Comment by clockworkgeek** [comment]
This is good, helpful research but I have some time away and won't be able to look into this for a couple of weeks.  Hopefully you can make do without this for a while.
